apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: CLUSTER-ID
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: test-ms
  namespace: default
spec:
  replicas: 12
  deletePolicy: Oldest
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: CLUSTER-ID
      machine.openshift.io/cluster-api-machineset: CLUSTER-ID-worker-e16as-REGION1
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: CLUSTER-ID
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machinegroup: worker-e16as
        machine.openshift.io/cluster-api-machineset: CLUSTER-ID-worker-e16as-REGION1
    spec:
      metadata:
        labels:
          paas.amadeus.net/type: worker-e16as
      providerSpec:
        value:
          acceleratedNetworking: true
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          capacityReservationGroupID: /subscriptions/1475241891-4e59-abaf-56cbb0b8a331/resourceGroups/capacity-reservation-rg/providers/Microsoft.Compute/capacityReservationGroups/global-capacity-reservation-group
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image:
            offer: ""
            publisher: ""
            resourceID: IMAGERESOURCEID
            sku: ""
            version: ""
          kind: AzureMachineProviderSpec
          location: REGION
          managedIdentity: CLUSTER-ID-identity
          metadata:
            creationTimestamp: null
          networkResourceGroup: NETWORKRESOURCEGROUP
          osDisk:
            diskSizeGB: 1024
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          resourceGroup: RESOURCEGROUP
          subnet: paas
          userDataSecret:
            name: worker-user-data
          vmSize: Standard_E16as_v4
          vnet: VNET
          zone: "1"
